# Stock Market Prediction on Nifty50 Dataset (2000-2020)

## Data Preprocessing

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv(r'F:/projects/stock market prediction/NIFTY50_all.csv')
X = dataset.iloc[:, [4,5,6]].values
y = dataset.iloc[:, 8].values
print(dataset.shape)

(223422, 15)


In [32]:
sample= dataset.iloc[0:150, :]
sample.to_csv(r'F:/projects/stock market prediction/sm.csv',index=False)

In [3]:
print(X)
print(X.shape)

[[ 770.   1050.    770.  ]
 [ 984.    990.    874.  ]
 [ 909.    914.75  841.  ]
 ...
 [ 175.5   180.75  174.15]
 [ 174.9   175.1   167.8 ]
 [ 174.    175.8   169.6 ]]
(223422, 3)


In [4]:
print(y)
print(y.shape)

[962.9  893.9  884.2  ... 176.25 172.05 171.1 ]
(223422,)


### Splitting the Dataset to Training and Test Set

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
y_train.shape

(167566,)

In [7]:
X_test.shape

(55856, 3)

In [8]:
y_test.shape

(55856,)

In [9]:
X_train.shape

(167566, 3)

# 1.Multiple Linear Regression

In [10]:
from sklearn.linear_model import LinearRegression
regressor1=LinearRegression()
regressor1.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
y_pred1=regressor1.predict(X_test)
print(y_pred1)
print(y_test)

[ 732.24021723 2362.41434097  891.35794775 ...  123.51686961 1204.09205622
  509.93017455]
[ 745.5  2296.65  893.15 ...  123.6  1209.8   509.95]


In [12]:
regressor1.predict([[770,1050,770]])

array([975.71562405])

### Calculating Errors

In [13]:
#Mean Squared Error
from sklearn.metrics import mean_squared_error
MSE1=mean_squared_error(y_test,y_pred1)
print(MSE1)

512.9912393130551


In [14]:
#Root Mean Squared Error
from math import sqrt
RMSE1 = sqrt(MSE1)
print(RMSE1)

22.649309908097752


In [15]:
#Mean Absolute Error
from sklearn.metrics import mean_absolute_error
MAE1=mean_absolute_error(y_test, y_pred1)
print(MAE1)

7.524139532634633


# 2.Decision Tree Regression

In [16]:
#fitting decision tree into dataset
from sklearn.tree import DecisionTreeRegressor
regressor2=DecisionTreeRegressor(random_state=0)
regressor2.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=0, splitter='best')

In [17]:
y_pred2=regressor2.predict(X_test)
print(y_pred2)
print(y_test)

[ 739.7  2339.9   885.15 ...  123.6  1209.55  488.  ]
[ 745.5  2296.65  893.15 ...  123.6  1209.8   509.95]


In [18]:
regressor2.predict([[770,1050,770]])

array([782.85])

### Calculating Errors

In [19]:
#Mean Squared Error
from sklearn.metrics import mean_squared_error
MSE2=mean_squared_error(y_test,y_pred2)
print(MSE2)

1251.233108421668


In [20]:
#Root Mean Squared Error
from math import sqrt
RMSE2 = sqrt(MSE2)
print(RMSE2)

35.372773547202485


In [21]:
#Mean Absolute Error
from sklearn.metrics import mean_absolute_error
MAE2=mean_absolute_error(y_test, y_pred2)
print(MAE2)

10.370896874701613


# 3.Random Forest Regression

In [22]:
# Fitting Random Forest Regression to the dataset
from sklearn.ensemble import RandomForestRegressor
regressor3 = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor3.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [23]:
y_pred3=regressor3.predict(X_test)
print(y_pred3)
print(y_test)

[ 742.615 2354.96   887.625 ...  123.525 1200.87   517.59 ]
[ 745.5  2296.65  893.15 ...  123.6  1209.8   509.95]


In [24]:
regressor3.predict([[770,1050,770]])

array([842.92])

### Calculating Errors

In [25]:
#Mean Squared Error
from sklearn.metrics import mean_squared_error
MSE3=mean_squared_error(y_test,y_pred3)
print(MSE3)

849.7229461627232


In [26]:
#Root Mean Squared Error
from math import sqrt
RMSE3 = sqrt(MSE3)
print(RMSE3)

29.150007652875896


In [27]:
#Mean Absolute Error
from sklearn.metrics import mean_absolute_error
MAE3=mean_absolute_error(y_test, y_pred3)
print(MAE3)

8.454775201353936


# 4.XGBoost Regression

In [28]:
import xgboost

In [29]:
from xgboost import XGBRegressor
regressor4=XGBRegressor()
regressor4.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=0, num_parallel_tree=1,
             objective='reg:squarederror', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [30]:
y_pred4=regressor4.predict(X_test)
print(y_pred4)
print(y_test)

[ 739.6276  2460.5334   882.33136 ...  127.79331 1220.0597   511.5599 ]
[ 745.5  2296.65  893.15 ...  123.6  1209.8   509.95]


In [31]:
regressor4.predict([[770,1001,22]])

TypeError: Input data can not be a list.

### Calculating Errors 

In [ ]:
#Mean Squared Error
from sklearn.metrics import mean_squared_error
MSE4=mean_squared_error(y_test,y_pred4)
print(MSE4)

In [ ]:
#Root Mean Squared Error
from math import sqrt
RMSE4 = sqrt(MSE4)
print(RMSE4)

In [ ]:
#Mean Absolute Error
from sklearn.metrics import mean_absolute_error
MAE4=mean_absolute_error(y_test, y_pred4)
print(MAE4)

# Comparing all Models

In [ ]:
print('Comparing all Models\n')
print('                                   MSE          RSME          MAE')
print('---------------------------------------------------------------------')
print('Multiple Linear Regression     :  {:.4f}'.format(MSE1)+'      {:.4f}'.format(RMSE1)+'      {:.4f}'.format(MAE1))
print('Decision Tree Regression       : {:.4f}'.format(MSE2)+'      {:.4f}'.format(RMSE2)+'      {:.4f}'.format(MAE2))
print('Random Forest Regression       :  {:.4f}'.format(MSE3)+'      {:.4f}'.format(RMSE3)+'      {:.4f}'.format(MAE3))
print('XGBoost Regression             :  {:.4f}'.format(MSE4)+'      {:.4f}'.format(RMSE4)+'      {:.4f}'.format(MAE4))